version: "2"
services:
  app:
    build: .
    links:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo/weatherapp
      # - APP_PUBLIC_URL=
    ports:
      - "80:3000"
  mongo:
    image: mongo
    volumes_from:
      - mongodata
    ports:
      - "27017:27017"
    command: --smallfiles
  mongodata:
    image: mongo
    volumes:
      - /data/db
    command: echo 'mongodata conatainer'
